# Generated by Django 4.0.1 on 2022-12-26 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_alter_tarefa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_de_conclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 26, 21, 56, 30, 797309, tzinfo=utc), null=True),
        ),
    ]
