# Generated by Django 4.0.1 on 2022-12-26 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_tarefa_data_tarefa_data_de_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_de_conclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 26, 21, 57, 0, 700607, tzinfo=utc), null=True),
        ),
    ]
